server:
  port: 8081
prop:
  upload-folder: E:/User/Desktop/campus/school/public/campusUploadImg/
  upload-imgfolder: E:/User/Desktop/campus/school/src/assets/img/userAvatar
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/campus?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  redis:

    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 -1 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password:
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


mybatis-plus:

  type-aliases-package: com.example.server.model
  mapper-locations: classpath:com/example/server/mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: false
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true

#
#jwt:
#  #JWT 存储的请求头
#  tokenHeader: Authorization
#  #JWT 加解密使用的秘钥
#  secret: yeb-secret
#  #JWT 的超期时间(60*60*24)
#  expiration: 86400
#  #JWT 负载中拿到的开头
#  tokenHead: Bearer
#alipay:
#  aliPayUrl: https://openapi.alipaydev.com/gateway.do
#  appId: 2021000116671801
#  appPrivateKey:
#  alipayPublicKey:
#  notifyUrl: http://fd3b3i.natappfree.cc/aply/notify
#  format: JSON
#  SIGN_TYPE: RSA2
